language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
  - php: 7.2
  - php: hhvm

before_script:
  - composer update
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then echo 'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi

script: php vendor/phpunit/phpunit/phpunit

